---
title: "vignette_FIHR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette_FIHR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



```{r setup}
library(FIHR)
```

Inference for linear functional in high-dimensional linear regression model

```{r Linear Functional Linear Model}
#X = matrix(sample(-2:2,100*400,replace = TRUE),nrow=100,ncol=400)
library(MASS)
A1gen <- function(rho,p){
  A1=matrix(0,p,p)
  for(i in 1:p){
    for(j in 1:p){
      A1[i,j]<-rho^(abs(i-j))
    } 
  }
  A1
}
mu <- rep(0,400)
mu[1:5] <- c(1:5)/5
rho = 0.5
Cov <- (A1gen(rho,400))/2
beta <- rep(0,400)
beta[1:10] <- c(1:10)/5
X <- MASS::mvrnorm(100,mu,Cov)
y = X%*%beta + rnorm(100)
Est = FIHR::LF_Inference(X = X, y = y, loading = c(1,rep(0,399)), intercept = TRUE)
Est$prop.est
Est$se
```

Inference for linear functional in high-dimensional logistic regression model

```{r Linear Functional Logistic Model}
library(MASS)
A1gen <- function(rho,p){
  A1=matrix(0,p,p)
  for(i in 1:p){
    for(j in 1:p){
      A1[i,j]<-rho^(abs(i-j))
    } 
  }
  A1
}
mu <- rep(0,400)
rho = 0.5
Cov <- (A1gen(rho,400))/2
beta <- rep(0,400)
beta[1:10] <- c(1:10)/5
X <- MASS::mvrnorm(100,mu,Cov)
exp_val <- X%*%beta
prob <- exp(exp_val)/(1+exp(exp_val))
y <- rbinom(100,1,prob)
Est = FIHR::LF_Inference_logistic(X = X, y = y, loading = c(1,rep(0,399)), intercept = TRUE, weight = rep(1,100))
Est$prop.est
Est$se
```

Inference for sqaure norm of the regression vector in high-dimensional linear model

```{r Group Norm Linear Model}
library(MASS)
A1gen <- function(rho,p){
  A1=matrix(0,p,p)
  for(i in 1:p){
    for(j in 1:p){
      A1[i,j]<-rho^(abs(i-j))
    } 
  }
  A1
}
rho = 0.6
Cov <- (A1gen(rho,400))
mu <- rep(0,400)
mu[1:5] <- c(1:5)/5
beta <- rep(0,400)
beta[25:50] <- 0.08
X <- MASS::mvrnorm(100,mu,Cov)
y <- X%*%beta + rnorm(100)
test.set <- c(30:100)
Est = FIHR::QF_Norm(X = X, y = y, test.set=test.set)
Est$prop.est
Est$se
```

Inference for quadratic functional in high-dimensional linear model

```{r Group Linear Model}
library(MASS)
A1gen <- function(rho,p){
  A1=matrix(0,p,p)
  for(i in 1:p){
    for(j in 1:p){
      A1[i,j]<-rho^(abs(i-j))
    } 
  }
  A1
}
rho = 0.6
Cov <- (A1gen(rho,400))
mu <- rep(0,400)
mu[1:5] <- c(1:5)/5
beta <- rep(0,400)
beta[25:50] <- 0.08
X <- MASS::mvrnorm(100,mu,Cov)
y <- X%*%beta + rnorm(100)
test.set <- c(30:100)
Est = FIHR::QF(X = X, y = y, test.set=test.set)
Est$prop.est
Est$se
```
